version: '2'
services:
  app:
    image: first-app
    ports:
    - "8081:8081"
    depends_on:
    - mypostgres
  mypostgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb